### ISSUE TITLE
numpy.float64 not iterable

### ISSUE THREAD

**Issue by Elfoniok** [golemfactory/golem-verificator#55]
Happens randomly in tests

Traceback (most recent call last):
  File "/golem/work/job.py", line 71, in <module>
    params.xres, params.yres)
  File "/golem/work/job.py", line 60, in run_img_compare_task
    output_filename_path=file_path)
  File "/golem/scripts/img_metrics_calculator.py", line 52, in compare_crop_window
    default_metrics = compare_images(cropped_img, default_crop, available_metrics)
  File "/golem/scripts/img_metrics_calculator.py", line 218, in compare_images
    result = metric_class.compute_metrics(image_a, image_b)
  File "/golem/scripts/metrics/wavelet.py", line 129, in compute_metrics
    freqs = calculate_frequencies( coeff1, coeff2 )
  File "/golem/scripts/metrics/wavelet.py", line 50, in calculate_frequencies
    sum_coeffs1 = sum( sum( sum( abs_coeff1 ) ) )
TypeError: 'numpy.float64' object is not iterable

**Comment by magdasta** [comment]
Please check if it still occurs on revision https://github.com/golemfactory/golem/commit/c8228c26b0cea7ba826ec2a36d4212a403ab54fb by running test_good_image test multiple times in a loop.
